### ISSUE TITLE
Close this repo?

### ISSUE THREAD

**Issue by lukemelia** [mikegrassotti/ember-cli-filepicker#1]
Howdy @mikegrassotti! I suggest you consider either closing, renaming, and/or clearly documenting that this repo is not associated with the ember-cli-filepicker npm module. I was a bit confused just now.

**Comment by mikegrassotti** [comment]
@lukemelia yeah good point. I'd been thinking of writing a filepicker addon but got distracted. totally forgot this repo existed, actually using the npm one for a couple projects it works great. deleting now...
